name: demo_widgets
description: A new Flutter project.
version: 0.5.0
homepage: https://github.com/yohom/demo_widgets

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  decorated_flutter: 0.46.15
  flutter_syntax_view: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
